version: "3.9"

networks:
  code_test:
volumes:
  esdata:
    driver: local
  mongo_data:

services:
  code_test:
    build: .
    restart: unless-stopped
    networks:
      - "code_test"
    ports:
      - "9267:9267"
    volumes:
      - .:/home/node/app
    env_file:
      - ./.env
    command: bash -c "npm i && npm run dev"
    depends_on:
      - mongodb
  mongodb:
    container_name: mongodb_code_test
    image: library/mongo:4.4.4
    volumes:
      - mongo_data:/data/db
    networks:
      - "code_test"
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
